INSERT INTO ingredients (name, category) VALUES
    ('Vodka', 'Spirit'),
    ('Gin', 'Spirit'),
    ('White Rum', 'Spirit'),
    ('Dark Rum', 'Spirit'),
    ('Tequila Blanco', 'Spirit'),
    ('Tequila Reposado', 'Spirit'),
    ('Bourbon', 'Spirit'),
    ('Scotch Whisky', 'Spirit'),
    ('Brandy', 'Spirit'),
    ('Mezcal', 'Spirit'),
    ('Triple Sec', 'Liqueur'),
    ('Cointreau', 'Liqueur'),
    ('Amaretto', 'Liqueur'),
    ('Kahlua', 'Liqueur'),
    ('Baileys Irish Cream', 'Liqueur'),
    ('Campari', 'Liqueur'),
    ('Aperol', 'Liqueur'),
    ('Dry Vermouth', 'Liqueur'),
    ('Sweet Vermouth', 'Liqueur'),
    ('Tonic Water', 'Mixer'),
    ('Club Soda', 'Mixer'),
    ('Ginger Beer', 'Mixer'),
    ('Ginger Ale', 'Mixer'),
    ('Cola', 'Mixer'),
    ('Lemon-Lime Soda', 'Mixer'),
    ('Lime Juice', 'Juice'),
    ('Lemon Juice', 'Juice'),
    ('Orange Juice', 'Juice'),
    ('Cranberry Juice', 'Juice'),
    ('Pineapple Juice', 'Juice'),
    ('Grapefruit Juice', 'Juice'),
    ('Simple Syrup', 'Syrup'),
    ('Grenadine', 'Syrup'),
    ('Agave Syrup', 'Syrup'),
    ('Elderflower Syrup', 'Syrup'),
    ('Angostura Bitters', 'Bitters'),
    ('Orange Bitters', 'Bitters'),
    ('Mint Leaves', 'Garnish'),
    ('Lime Wedge', 'Garnish'),
    ('Lemon Twist', 'Garnish'),
    ('Maraschino Cherry', 'Garnish'),
    ('Olive', 'Garnish')
ON CONFLICT (name) DO NOTHING;
