name: Deploy BarBud Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd ~/apps/BarBud-Backend
          git pull origin main
          docker compose up -d --build
          docker image prune -f